### ISSUE TITLE
没能获取到wechatSESS_ID

### ISSUE THREAD

**Issue by just2022try** [MikeWang000000/GoLibCookie#2]
获取到了两个SERVERID，而没有wechatSESS_ID

**Comment by MikeWang000000** [comment]
这是新版网页端的Cookie，使用Authorization作为会话识别。
如果想获取wechatSESS_ID，请将下方`/urlNew/`替换为`/url/`，再运行Python脚本。
https://github.com/MikeWang000000/GoLibCookie/blob/1d764b4ba9af71983ed3a105fe3feaaede1cf076/golib_cookie.py#L20

**Comment by just2022try** [comment]
明白了，感谢大佬，祝生活顺利学业有成。
