### ISSUE TITLE
获取wechatSESS_ID后使用keep_session.py无法保活,会提示过期

### ISSUE THREAD

**Issue by 56luffy** [MikeWang000000/GoLibCookie#7]
如题,按照SERVERID=;Hm_lpvt_7ecd21a13263a714793f376c18038a87=;wechatSESS_ID=;Hm_lvt_7ecd21a13263a714793f376c18038a87=;FROM_TYPE=weixin的格式作为字符串写入程序

**Comment by MikeWang000000** [comment]
此脚本只针对 v3 api ，v2 api 已经弃用。请参考其他的 GitHub 仓库。
