### ISSUE TITLE
无法获取可用cookie

### ISSUE THREAD

**Issue by iErics** [MikeWang000000/GoLibCookie#8]
现在只能获取到SERVERID=d3936289adfff6c3874a2579058ac651|1663480509|1663480509这串cookie，抓包的Header中有两个Set-Cookie，但是只能获取到第二个
![抓包截图](https://user-images.githubusercontent.com/42070668/190888495-167aec1f-8281-4f5c-b8ac-4484351b3070.png)

**Comment by MikeWang000000** [comment]
参考 readme 中的 “网页示例”。
如果 demo 工作正常，那么便不是本项目的问题。
我不能复现。

**Comment by iErics** [comment]
找到原因了，因环境问题第一次请求时都会出现SSL错误：
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`
如果用同一个URL进行第二次请求不会报错，但无法返回正确的Cookie信息，添加如下代码解决SSL错误已经可以正常返回Cookie
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
